/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bot.proto */

#ifndef PROTOBUF_C_bot_2eproto__INCLUDED
#define PROTOBUF_C_bot_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BotConnect BotConnect;
typedef struct _BotMovement BotMovement;
typedef struct _BotDisconnect BotDisconnect;
typedef struct _ConnectRepply ConnectRepply;


/* --- enums --- */

typedef enum _DirectionMove {
  DIRECTION_MOVE__UP = 0,
  DIRECTION_MOVE__DOWN = 1,
  DIRECTION_MOVE__LEFT = 2,
  DIRECTION_MOVE__RIGHT = 3,
  DIRECTION_MOVE__HOLD = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION_MOVE)
} DirectionMove;

/* --- messages --- */

/*
 * MESSAGES SENT BY BOT CLIENT
 */
struct  _BotConnect
{
  ProtobufCMessage base;
  size_t n_score;
  uint32_t *score;
};
#define BOT_CONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_connect__descriptor) \
    , 0,NULL }


struct  _BotMovement
{
  ProtobufCMessage base;
  size_t n_id;
  uint32_t *id;
  size_t n_token;
  uint32_t *token;
  size_t n_movement;
  DirectionMove *movement;
};
#define BOT_MOVEMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_movement__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  _BotDisconnect
{
  ProtobufCMessage base;
  size_t n_id;
  uint32_t *id;
  size_t n_token;
  uint32_t *token;
};
#define BOT_DISCONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bot_disconnect__descriptor) \
    , 0,NULL, 0,NULL }


/*
 * MESSAGES SENT BY THE SERVER
 */
struct  _ConnectRepply
{
  ProtobufCMessage base;
  size_t n_id;
  uint32_t *id;
  size_t n_token;
  uint32_t *token;
};
#define CONNECT_REPPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connect_repply__descriptor) \
    , 0,NULL, 0,NULL }


/* BotConnect methods */
void   bot_connect__init
                     (BotConnect         *message);
size_t bot_connect__get_packed_size
                     (const BotConnect   *message);
size_t bot_connect__pack
                     (const BotConnect   *message,
                      uint8_t             *out);
size_t bot_connect__pack_to_buffer
                     (const BotConnect   *message,
                      ProtobufCBuffer     *buffer);
BotConnect *
       bot_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bot_connect__free_unpacked
                     (BotConnect *message,
                      ProtobufCAllocator *allocator);
/* BotMovement methods */
void   bot_movement__init
                     (BotMovement         *message);
size_t bot_movement__get_packed_size
                     (const BotMovement   *message);
size_t bot_movement__pack
                     (const BotMovement   *message,
                      uint8_t             *out);
size_t bot_movement__pack_to_buffer
                     (const BotMovement   *message,
                      ProtobufCBuffer     *buffer);
BotMovement *
       bot_movement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bot_movement__free_unpacked
                     (BotMovement *message,
                      ProtobufCAllocator *allocator);
/* BotDisconnect methods */
void   bot_disconnect__init
                     (BotDisconnect         *message);
size_t bot_disconnect__get_packed_size
                     (const BotDisconnect   *message);
size_t bot_disconnect__pack
                     (const BotDisconnect   *message,
                      uint8_t             *out);
size_t bot_disconnect__pack_to_buffer
                     (const BotDisconnect   *message,
                      ProtobufCBuffer     *buffer);
BotDisconnect *
       bot_disconnect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bot_disconnect__free_unpacked
                     (BotDisconnect *message,
                      ProtobufCAllocator *allocator);
/* ConnectRepply methods */
void   connect_repply__init
                     (ConnectRepply         *message);
size_t connect_repply__get_packed_size
                     (const ConnectRepply   *message);
size_t connect_repply__pack
                     (const ConnectRepply   *message,
                      uint8_t             *out);
size_t connect_repply__pack_to_buffer
                     (const ConnectRepply   *message,
                      ProtobufCBuffer     *buffer);
ConnectRepply *
       connect_repply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connect_repply__free_unpacked
                     (ConnectRepply *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BotConnect_Closure)
                 (const BotConnect *message,
                  void *closure_data);
typedef void (*BotMovement_Closure)
                 (const BotMovement *message,
                  void *closure_data);
typedef void (*BotDisconnect_Closure)
                 (const BotDisconnect *message,
                  void *closure_data);
typedef void (*ConnectRepply_Closure)
                 (const ConnectRepply *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction_move__descriptor;
extern const ProtobufCMessageDescriptor bot_connect__descriptor;
extern const ProtobufCMessageDescriptor bot_movement__descriptor;
extern const ProtobufCMessageDescriptor bot_disconnect__descriptor;
extern const ProtobufCMessageDescriptor connect_repply__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_bot_2eproto__INCLUDED */
